import { RefObject, useEffect, useRef } from "react";
import { formatTime } from "../lib/stats";
import type { Locale } from "../lib/i18n";
import { tr } from "../lib/i18n";

interface Props { accuracy:number; status:"idle"|"running"|"finished"; duration:number; liveCharCountRef:RefObject<number>; startTimeRef:RefObject<number|null>; focusMode?:boolean; locale?:Locale; }
export default function LiveMetrics({ accuracy,status,duration,liveCharCountRef,startTimeRef,focusMode=false,locale="en" }:Props){
 const actualWpmElementRef=useRef<HTMLSpanElement|null>(null); const timeElementRef=useRef<HTMLSpanElement|null>(null);
 useEffect(()=>{let animationFrame=0,mounted=true,lastWpm="0.0",lastTime=formatTime(duration);const render=()=>{if(!mounted)return;const ae=actualWpmElementRef.current,te=timeElementRef.current,start=startTimeRef.current;if(status!=="running"||start===null){if(ae&&ae.textContent!=="0.0")ae.textContent="0.0";if(te&&te.textContent!==lastTime){lastTime=formatTime(duration);te.textContent=lastTime;}return;}const elapsedMs=Math.max(0,Date.now()-start),elapsedMinutes=elapsedMs/60000,typedCharacters=liveCharCountRef.current;const wpm=elapsedMinutes>0?Math.max(0,Math.round((typedCharacters/5/elapsedMinutes)*10)/10):0,nextWpm=wpm.toFixed(1);if(ae&&nextWpm!==lastWpm){lastWpm=nextWpm;ae.textContent=nextWpm;}const nextTime=formatTime(Math.ceil(Math.max(0,duration*1000-elapsedMs)/1000));if(te&&nextTime!==lastTime){lastTime=nextTime;te.textContent=nextTime;}animationFrame=requestAnimationFrame(render);};render();return()=>{mounted=false;cancelAnimationFrame(animationFrame);};},[duration,liveCharCountRef,startTimeRef,status]);
 const cell=focusMode?"flex min-h-[112px] flex-col items-center justify-center gap-2 px-3 py-5 sm:min-h-[132px] sm:py-6":"flex min-h-[72px] flex-col items-center justify-center gap-1 px-2.5 py-3 sm:min-h-[78px] sm:py-3.5";
 return <div className="metric-surface grid grid-cols-3 divide-x divide-hairline rounded-[24px] border border-hairline bg-canvas-soft">
  <div className={cell}><span className="font-label text-text-muted">{tr(locale,"tester","actualWpm")}</span><span ref={actualWpmElementRef} aria-live="off" className={focusMode?"font-mono text-4xl font-bold tabular-nums text-accent sm:text-5xl lg:text-6xl":"font-mono text-2xl font-bold tabular-nums text-accent sm:text-[28px]"}>0.0</span></div>
  <div className={cell}><span className="font-label text-text-muted">{tr(locale,"tester","accuracy")}</span><span className={focusMode?"font-mono text-4xl font-bold tabular-nums text-ink sm:text-5xl lg:text-6xl":"font-mono text-2xl font-bold tabular-nums text-ink sm:text-[28px]"}>{accuracy}%</span></div>
  <div className={cell}><span className="font-label text-text-muted">{tr(locale,"tester","time")}</span><span ref={timeElementRef} className={focusMode?"font-mono text-4xl font-bold tabular-nums text-ink sm:text-5xl lg:text-6xl":"font-mono text-2xl font-bold tabular-nums text-ink sm:text-[28px]"}>{formatTime(duration)}</span></div>
 </div>;
}