export default function PrivacyPolicyPage() {
  return (
    <section className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="rounded-[24px] border border-hairline bg-canvas p-6 shadow-sm sm:p-10">
        <p className="font-label text-accent">Legal</p>
        <h1 className="mt-3 font-heading-3 text-ink">PRIVACY POLICY</h1>
        <p className="mt-3 font-caption text-text-faint">Last updated: September 4, 2026</p>
        <div className="mt-8 space-y-6 font-body text-text-muted">
          <div><h2 className="font-heading-5 text-ink">Typing Tests Without an Account</h2><p className="mt-2">You can take a typing test on FreeTypingTestGoat without signing in. Anonymous test results are shown to you during and after the test, but are not saved to an account history, associated with an account, or included on the leaderboard.</p></div>
          <div><h2 className="font-heading-5 text-ink">Google Sign-In and Account Information</h2><p className="mt-2">Google Sign-In is optional. If you choose to sign in, Google and our authentication provider, Supabase, process the information needed to authenticate your account. This may include your email address, Google profile or provider identity information, and authentication identifiers. We use this information to operate your signed-in account and its related features.</p></div>
          <div><h2 className="font-heading-5 text-ink">Progress and Leaderboard Information</h2><p className="mt-2">A signed-in account is required for account-based progress tracking and leaderboard participation. When those features are used, we may store typing-performance information linked to your account. Leaderboard results may publicly display your chosen username, WPM, accuracy, difficulty, and the date of the result. Choose a username you are comfortable sharing publicly.</p></div>
          <div><h2 className="font-heading-5 text-ink">Cookies, Local Storage, Analytics, and Advertising</h2><p className="mt-2">We may use cookies, local storage, and similar technologies to operate the site, remember browser preferences, maintain sign-in sessions, understand site usage, and support advertising. We use Google Analytics to measure site usage and may use Google AdSense to display advertising. Google and other third-party vendors may use cookies or similar technologies to serve and measure ads, including ads based on a user's prior visits to this or other websites, subject to applicable consent requirements and their own policies.</p><p className="mt-2">Where required by applicable law or Google's publisher requirements, advertising and related technologies are used only after the required consent choices have been obtained through the site's consent mechanism. You can manage many cookies through your browser settings and can manage Google's personalized advertising choices through <a href="https://adssettings.google.com/" target="_blank" rel="noreferrer" className="text-accent hover:underline">Google Ads Settings</a>. You can also learn about choices for some third-party personalized advertising at <a href="https://www.aboutads.info/choices/" target="_blank" rel="noreferrer" className="text-accent hover:underline">aboutads.info</a>.</p></div>
          <div><h2 className="font-heading-5 text-ink">Local Browser Data and Typing Content</h2><p className="mt-2">Your difficulty and duration preferences and personal-best scores may be stored locally in your browser so they can be restored on that device. This device-level data is not account history. Custom text you paste into custom typing mode is processed in your browser and is not transmitted to our servers by the typing tester.</p></div>
          <div><h2 className="font-heading-5 text-ink">How We Use and Share Information</h2><p className="mt-2">We use account and typing information to provide authentication, saved-progress, leaderboard, analytics, and site-operation features. We do not sell your personal information. We do not use Google account information for unrelated advertising or marketing. Public leaderboard information is shared only as described above. Third-party services may process information according to their own privacy policies.</p></div>
          <div><h2 className="font-heading-5 text-ink">Data Deletion and Your Choices</h2><p className="mt-2">You may request deletion of your account, username, and account-linked progress data by contacting us at the address below. We may need to verify that the request comes from the account holder before completing it. You can also control many browser-level storage choices through your browser settings.</p></div>
          <div><h2 className="font-heading-5 text-ink">Changes to This Policy</h2><p className="mt-2">We may update this Privacy Policy as FreeTypingTestGoat evolves. Any updated version will be published on this page.</p></div>
          <div><h2 className="font-heading-5 text-ink">Questions</h2><p className="mt-2">If you have questions about this Privacy Policy or want to request deletion, please contact us at <a href="mailto:typeittestit@gmail.com" className="text-accent hover:underline">typeittestit@gmail.com</a>.</p></div>
        </div>
      </div>
    </section>
  );
}
